animate99/animate99/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("apps.accounts.urls")),
    path("", include("apps.main.urls")),
    path("blog/", include("apps.blog.urls")),
    path('google-auth/', include('allauth.urls')),
    path("dashboard/", include("apps.user_review.urls")),
    
    
]

animate99/apps/accounts/urls.py
from django.urls import include, path
from .views import register_view, login_view, logout_user, reset_view, forgot_view

app_name = 'accounts'

urlpatterns = [
    path('register/', register_view, name='register'),
    path('login/', login_view, name="login" ),
    path('logout/', logout_user, name="logout" ),
    path('forgotpassword/', forgot_view, name="forgotpassword" ),
    path('resetpassword/', reset_view, name="resetpassword" ),
    
]

animate99/apps/main/urls.py
from django.urls import path
from .views import home, documentation,download, support,download_file

urlpatterns = [
     path("", home, name='home' ),
     path("documentation", documentation, name='documentation' ),
     path("download", download, name='download' ),
     path("support", support, name='support' ),
     path('downloadfile', download_file, name="download-file" )

]

animate99/apps/main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse, FileResponse
from django.core.mail import send_mail, BadHeaderError
from django.contrib.auth.decorators import login_required
import mimetypes
import os
from pathlib import Path
# Import HttpResponse module
from django.http.response import HttpResponse



BASE_DIR = Path(__file__).resolve().parent.parent

# Create your views here.
def home (request):
    return render(request, 'main/home.html',)

def documentation (request):
    return render(request, 'main/documentation.html',)

@login_required
def download (request):
    return render(request, 'main/download.html',)

@login_required
def download_file(request):
    obj = BASE_DIR
    filename = 'script.js'
    response = FileResponse(open(filename, 'rb'))
    return response

def support (request):
    if request.method == 'POST':
        name = request.POST.get('name')
        email = request.POST.get('email')
        textarea = request.POST.get('textarea')
        
        body = {
            'name' : name,
            'email': email,
            'textarea': textarea,
        }
        
        # message = "\n".join(body.values())
        
        message = f"{body['name']} \n {body['email']} \n{body['textarea']}"   
        send_mail("User Support Enquiry", message, 'animatelib99@gmail.com', ['animatelib99@gmail.com'], fail_silently=False)
            
    return render(request, 'main/support.html')

animate99/templates/main/download.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="https://code.iconify.design/2/2.2.1/iconify.min.js"></script>
    <link rel="stylesheet" href="{% static 'main/download.css'  %}">
    <link rel="shortcut icon" href="{% static 'main/favicon.svg' %}" type="image/x-icon">
    <title>Download Animate99</title>
</head>

<body>
    <header>
        <nav>
            <div class="anim">
                <div class="logo-head">
                    <h1>Animate</h1>
                </div>
                <div class="logo-num"><a href="{% url 'home' %}">
                    <span>99</span></a></div>
            </div>
            <div class="nav-cont">
                {% if request.user.is_authenticated %}
                <ul class="nav-list">
                    <li class="nav-item"><a href="{% url 'home' %}">Home</a></li>
                    <li class="nav-item"><a href="{% url 'documentation' %}">Documentation</a></li>
                    <li class="nav-item"><a href="{% url 'library' %}">Dashboard</a></li>
                    <li class="nav-item"><a href="{% url 'support' %}">Support</a></li>
                </ul>
                {% else %}
                <ul class="nav-list">
                    <li class="nav-item"><a href="{% url 'home' %}">Home</a></li>
                    <li class="nav-item"><a href="{% url 'documentation' %}">Documentation</a></li>
                    <li class="nav-item"><a href="{% url 'download' %}">Download</a></li>
                    <li class="nav-item"><a href="{% url 'support' %}">Support</a></li>
                </ul>
                {% endif %}
                <div class="btns">
                    {% if request.user.is_authenticated %}
                    <a href="{% url 'download' %}"><button class="btn-head-2">Download</button></a>
                    
                    {% else %}
                    <a href="{% url 'accounts:login' %}"><button class="btn-head">Sign In</button></a>
                    <a href='..\accounts\register'><button class="btn-head-2">Register</button></a>
                    {% endif %}
                </div>
            </div>
        </nav>
        <div class="content">
            <h1>Ready to use our library?</h1>
            <p>Register with Animate99 to gain access to our library of animations. Make your programs more interactive
                when you
                implement our animations on your next web project!</p>

            <a href="{% url 'download-file' %}" download><button class="down-btn">Download Library <span class="iconify" data-icon="el:download-alt"></span></button></a>

            

        </div>
    </header>















    <div class="footer">
        <div class="footer-top">
            <div class="foot-top-left">
                <div class="logo-foot">
                    <h1>Animate</h1>
                    <div class="logo-num"><span>99</span></div>
                </div>
                <div class="foot-top-text">
                    <p>
                        Animate99 is an animation library created by Team 99 as a
                        necessary requirement to complete the I4GxZuri Internship program.
                    </p>
                </div>
            </div>
            <div class="foot-top-right">
                <div class="foot-top-right-1">
                    <h2>Navigation</h2>
                    <a href="{% url 'home' %}">
                        <p>Home</p>
                    </a>
                    <a href="{% url 'documentation' %}">
                        <p>Documentation</p>
                    </a>
                    <a href="{% url 'support' %}">
                        <p>Support</p>
                    </a>
            
                </div>
                <div class="foot-top-right-2">
                    <h2>Resources</h2>
                    <a href="https://github.com/zuri-training/Team99_anima_lib/graphs/contributors">
                        <p>Team</p>
                    </a>
                   
                    <a href="{% url 'download' %}">
                        <p>Download</p>
                    </a>
                </div>
                <div class="foot-top-right-3">
                    <h2>Installation</h2>
                    <a href="{% url 'download' %}">
                        <p>How to install</p>
                    </a>
                </div>
            </div>
            </div>
        </div>
        <div class="footer-mid">
            <div class="footer-mid-top">
                <p>v1.0</p>
                <div class="create">
                    <p>Created by Team99</p>
                </div>
                <p>2022</p>
            </div>
    
            <div class="footer-mid-bottom">
                <p>&copy;ZuriTeam</p>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <p>
            Animate99 is a Zuri project animation library. You can use it freely,
            respecting the terms included in the license file.
        </p>
    </div>
</body>

</html>

<!-- <a href="{% url 'accounts:logout' %}">Logout user</a> -->

animate99/templates/main/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Animate99</title>

    <script src="https://anima99.bitbucket.io/script.js"></script>
    <link rel="stylesheet" href="{% static 'main/style.css'  %}">
    <link rel="shortcut icon" href="{% static 'main/favicon.svg' %}" type="image/x-icon">
</head>

<body>
    <header>
        <nav>
            <div class="anim">
                <div class="logo-head">
                    <h1>Animate</h1>
                </div>
                <div class="logo-num"><a href="{% url 'home' %}"><span>99</span></a></div>
            </div>
            <div class="nav-cont">
                {% if request.user.is_authenticated %}
                <ul class="nav-list">
                    <li class="nav-item"><a href="{% url 'home' %}">Home</a></li>
                    <li class="nav-item"><a href="{% url 'documentation' %}">Documentation</a></li>
                    <li class="nav-item"><a href="{% url 'library' %}">Dashboard</a></li>
                    <li class="nav-item"><a href="{% url 'support' %}">Support</a></li>
                </ul>
                {% else %}
                <ul class="nav-list">
                    <li class="nav-item"><a href="{% url 'home' %}">Home</a></li>
                    <li class="nav-item"><a href="{% url 'documentation' %}">Documentation</a></li>
                    <li class="nav-item"><a href="{% url 'download' %}">Download</a></li>
                    <li class="nav-item"><a href="{% url 'support' %}">Support</a></li>
                </ul>
                {% endif %}
                <div class="btns">                   
                    {% if request.user.is_authenticated %}
                        <a href="{% url 'download' %}"><button class="btn-head-2">Download</button></a>
 
                    {% else %}
                    <a href="{% url 'accounts:login' %}"><button class="btn-head">Sign In</button></a>
                    <a href='..\accounts\register'><button class="btn-head-2">Register</button></a>
                    {% endif %}                    
                <div class="btns">

                </div>
            </div>
        </nav>
        <div class="header-info">
            <div class="header-info-text">
                <h1>
                    The Perfect<br />
                    <span class="header-text-js">JavaScript Animation</span><br />
                    Library For You.
                </h1>
                <p>Add cool animations to your program with ease and flexibility</p>
                {% if request.user.is_authenticated %}
                    <a href="{% url 'library' %}"><button class="btn-info-text">Go to dashboard &#129130;</button></a>
                {% else %}
                    <a href="{% url 'accounts:login' %}"><button class="btn-info-text">Get Started &#129130;</button></a>
                {% endif %}

            </div>
            <div class="header-info-image">
                <img src="{% static 'main/header-image.png'  %}" alt="Animation" id="headImg" onload="anima.flip('headImg',500, 2)" />
            </div>
        </div>
    </header>

    <div class="middle">
        <div class="middle-text">
            <h1>What is Animate99?</h1>
            <p>
                Animate99 is a JavaScript animation library built upon the Web
                Animations API in order to allow beginner developers create basic
                animations using <strong>simple yet powerful functions</strong> that
                are also customizable. It allows you to easily incorporate animations
                into your programs without the hassle of writing the code from
                scratch. Built into the library is a collection of functions written
                using normal language. The Animate99 library also provides the
                developer with substantial flexibility in how they choose to apply the
                animations to their programs.
            </p>
        </div>
        <div class="mid-box-1">
            <div class="box-1-image">
                <img src="{% static 'main/mid-dude.png'  %}" alt="male-icon" class="mid-icons" />
            </div>
            <div class="box-1-text">
                <h1>Register: Why You Should</h1>
                <p>
                    In order to get started using the Animate99 JavaScript library, you
                    will first need to register as a user on our website.
                </p>
                <a href='..\accounts\register'><button class="reg-btn">Register &#129130;</button></a>
            </div>
        </div>
        <div class="mid-box-2">
            <div class="box-2-text">
                <h1>How To: Documentation</h1>
                <p>
                    Check out our comprehensive documentation to quickly learn how to
                    start creating awesome animations with the Animate99 JavaScript
                    library!
                </p>
                <a href="{% url 'documentation' %}"><button class="doc-btn">Documentation &#129130;</button></a>
            </div>
            <div>
                <img src="{% static 'main/mid-hijabi.png'  %}" alt="female-icon" class="mid-icons" />
            </div>
        </div>
        <div class="mid-box-3">
            <div>
                <img src="{% static 'main/mid-girl.png'  %}" alt="female-icon" class="mid-icons" />
            </div>
            <div class="box-3-text">
                <h1>Usage Examples</h1>
                <p>
                    Not sure what kind of animations you'd like to create? Not to worry!
                    check out our interactive usage examples for some inspiration.
                </p>
                <a href="{% url 'accounts:login' %}"><button class="use-btn">Usage Examples &#129130;</button></a>
            </div>
        </div>
    </div>

    <div class="bottom">
        <div class="bottom-head">
            <h1>Hover on any of the boxes for some visuals!</h1>
        </div>

        <div class="carousel">
            <div class="bottom-left">
                <p>
                    Register or sign in now to have access to our full library of
                    customizable animations.
                </p>
                <a href="{% url 'accounts:login' %}"><button class="bottom-left-btn">View More &#129130;</button></a>
            </div>

            <div class="bottom-right">
                <div class="ball-1">
                    <div class="ball-cont-1">
                        <div class="ball" id="b-1" onmouseover="anima.shake('b-1', 500, 2)"></div>
                    </div>
                    <h2>Shake</h2>
                </div>
                <div class="ball-2">
                    <div class="ball-cont-2">
                        <div class="ball" id="b-2" onmouseover="anima.pulse('b-2', 800, 2)"></div>
                    </div>
                    <h2>Pulse</h2>
                </div>

                <div class="ball-3">
                    <div class="ball-cont-3">
                        <div class="ball" id="b-3" onmouseover="anima.bounce('b-3', 200, 4)"></div>
                    </div>
                    <h2>Bounce</h2>
                </div>
            </div>
        </div>

        <!-- <div class="carousel-btns">
        <div class="carousel-btn-1"><button>&#129168;</button></div>
        <div class="carousel-btn-2"><button>&#129170;</button></div>
      </div> -->
    </div>

    <div class="footer">
        <div class="footer-top">
            <div class="foot-top-left">
                <div class="logo-foot">
                    <h1>Animate</h1>
                    <div class="logo-num"><span>99</span></div>
                </div>
                <div class="foot-top-text">
                    <p>
                        Animate99 is an animation library created by Team 99 as a
                        necessary requirement to complete the I4GxZuri Internship program.
                    </p>
                </div>
            </div>
        <div class="foot-top-right">
            <div class="foot-top-right-1">
                <h2>Navigation</h2>
                <a href="{% url 'home' %}">
                    <p>Home</p>
                </a>
                <a href="{% url 'documentation' %}">
                    <p>Documentation</p>
                </a>
                <a href="{% url 'support' %}">
                    <p>Support</p>
                </a>
        
            </div>
            <div class="foot-top-right-2">
                <h2>Resources</h2>
                <a href="https://github.com/zuri-training/Team99_anima_lib/graphs/contributors">
                    <p>Team</p>
                </a>
                <a href="{% url 'download' %}">
                    <p>Download</p>
                </a>
            </div>
            <div class="foot-top-right-3">
                <h2>Installation</h2>
                <a href="{% url 'download' %}">
                    <p>How to install</p>
                </a>
            </div>
        </div>
        </div>
        <div class="footer-mid">
            <div class="footer-mid-top">
                <p>v1.0</p>
                <div class="create">
                    <p>Created by Team99</p>
                </div>
                <p>2022</p>
            </div>

            <div class="footer-mid-bottom">
                <p>&copy;ZuriTeam</p>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <p>
            Animate99 is a Zuri project animation library. You can use it freely,
            respecting the terms included in the license file.
        </p>
    </div>

   
</body>

</html>

animate99/templates/main/support.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Support</title>
    <link rel="stylesheet" href="{% static 'main/support.css'  %}">
    <link rel="shortcut icon" href="{% static 'main/favicon.svg' %}" type="image/x-icon">
</head>

<body>
    <header>
        <nav>
            <div class="anim">
                <div class="logo-head">
                    <h1>Animate</h1>
                </div>
                <div class="logo-num"><a href="{% url 'home' %}">
                    <span>99</span></a></div>
            </div>
            {% if request.user.is_authenticated %}
            <ul class="nav-list">
                <li class="nav-item"><a href="{% url 'home' %}">Home</a></li>
                <li class="nav-item"><a href="{% url 'documentation' %}">Documentation</a></li>
                <li class="nav-item"><a href="{% url 'library' %}">Dashboard</a></li>
                <li class="nav-item"><a href="{% url 'support' %}">Support</a></li>
            </ul>
            {% else %}
            <ul class="nav-list">
                <li class="nav-item"><a href="{% url 'home' %}">Home</a></li>
                <li class="nav-item"><a href="{% url 'documentation' %}">Documentation</a></li>
                <li class="nav-item"><a href="{% url 'download' %}">Download</a></li>
                <li class="nav-item"><a href="{% url 'support' %}">Support</a></li>
            </ul>
            {% endif %}

            <div class="btns">
                {% if request.user.is_authenticated %}
                <a href="{% url 'download' %}"><button class="btn-head">Download</button></a>
                
                {% else %}
                <a href="{% url 'accounts:login' %}"><button class="btn-head">Get Full Access</button></a>
                {% endif %}
                
            </div>
        </nav>
    </header>

    <div class="header-box-1">
        <div class="box-1-text">
            <h1>Welcome To Animate99 Support</h1>
            <p>Got a question? we are here to help!</p>
        </div>
    </div>

    <div class="container">
        <div class="header-box-2">
            <div class="box-2-text">
                <h1>Installation</h1>
                <p>Have installation issues? Click on the link to learn more</p>
                <a href="{% url 'documentation' %}"><button class="get-btn">Documentation</button></a>
            </div>
        </div>
        <div class="header-box-3">
            <div class="box-3-text">
                <h1>Library</h1>
                <p>Want to use our animations? Click the link to learn more</p>
                <a href="{% url 'download' %}"><button class="dow-btn">Download library</button></a>
            </div>
        </div>
        <div class="header-box-4">
            <div class="box-4-text">
                <h1>Available animations</h1>
                <p>View all the available animations, Click the link to learn more</p>
                <a href="{% url 'accounts:login' %}"><button class="us-btn">Usage Examples</button></a>
            </div>
        </div>
    </div>

    <div class="middle">
        <div class="middle-text">
            <h1>Can't find what you're looking for ?</h1>
            <p>
                Our goal is to help make your life easier so send us a mail and we
                will solve your problem.
            </p>
        </div>

        <div class="mid-box-1">
            <form class="contact-form" action="" method="POST">
                {% csrf_token %}
                <input type="text" name="name" id="name" placeholder="Name" required />
                <input type="email" name="email" placeholder="E-mail" required />
                <textarea name="textarea" id="" cols="30" rows="10" placeholder="Type your message" required></textarea>
                <p class="register">Are you a registered user ?</p>

                <div class="radioButtons">
                    <label for="html">
                        <input type="radio" id="html" name="fav_language" value="HTML" />Yes
                    </label>

                    <label for="css">
                        <input type="radio" id="css" name="fav_language" value="CSS" /> No
                    </label>
                </div>
                <button class="sub-btn">Submit</button>
            </form>
        </div>
    </div>

    <div class="footer">
        <div class="footer-top">
            <div class="foot-top-left">
                <div class="logo-foot">
                    <h1>Animate</h1>
                    <div class="logo-num"><span>99</span></div>
                </div>
                <div class="foot-top-text">
                    <p>
                        Animate99 is an animation library created by Team 99 as a
                        necessary requirement to complete the I4GxZuri Internship program.
                    </p>
                </div>
            </div>
            <div class="foot-top-right">
                <div class="foot-top-right-1">
                    <h2>Navigation</h2>
                    <a href="{% url 'home' %}">
                        <p>Home</p>
                    </a>
                    <a href="{% url 'documentation' %}">
                        <p>Documentation</p>
                    </a>
                    <a href="{% url 'support' %}">
                        <p>Support</p>
                    </a>
                
                </div>
                <div class="foot-top-right-2">
                    <h2>Resources</h2>
                    <a href="https://github.com/zuri-training/Team99_anima_lib/graphs/contributors">
                        <p>Team</p>
                    </a>
                    <a href="{% url 'download' %}">
                        <p>Download</p></a>
                </div>
                <div class="foot-top-right-3">
                    <h2>Installation</h2>
                    
                     <a href="{% url 'download' %}">
                        <p>How to install</p>
                    </a>
                </div>
            </div>
        </div>
        <div class="footer-mid">
            <div class="footer-mid-top">
                <p>v1.0</p>
                <div class="create">
                    <p>Created by Team99</p>
                </div>
                <p>2022</p>
            </div>
    
            <div class="footer-mid-bottom">
                <p>&copy;ZuriTeam</p>
            </div>
        </div>
    </div>
    <div class="footer-bottom">
        <p>
            Animate99 is a Zuri project animation library. You can use it freely,
            respecting the terms included in the license file.
        </p>
    </div>
</body>

</html>