animate99/animate99/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("accounts/", include("apps.accounts.urls")),
    path("", include("apps.main.urls")),
    path("blog/", include("apps.blog.urls")),
    path('google-auth/', include('allauth.urls')),
    path("dashboard/", include("apps.user_review.urls")),
    
    
]

animate99/apps/accounts/urls.py
from django.urls import include, path
from .views import register_view, login_view, logout_user, reset_view, forgot_view

app_name = 'accounts'

urlpatterns = [
    path('register/', register_view, name='register'),
    path('login/', login_view, name="login" ),
    path('logout/', logout_user, name="logout" ),
    path('forgotpassword/', forgot_view, name="forgotpassword" ),
    path('resetpassword/', reset_view, name="resetpassword" ),
    
]

animate99/apps/accounts/models.py
from email.policy import default
from django.db import models
from django.contrib.auth.models import AbstractUser
from .managers import CustomUserManager
from cloudinary.models import CloudinaryField

class CustomUser(AbstractUser):
    username=None
    first_name = None
    last_name = None
    email = models.EmailField(max_length=50, db_index=True, unique=True)
    name = models.CharField(max_length=200, db_index=True, blank=True)
    github_url = models.URLField(max_length=255, blank=True)
    project_url = models.URLField(max_length=255, blank=True)
    twitter_url = models.URLField(max_length=255, blank=True)
    image = CloudinaryField('image', null=True)
    
    
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []
    
    
    objects = CustomUserManager()
    
    class Meta:
        ordering = ["email"]
        verbose_name = "User"
        
    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

animate99/apps/accounts/forms.py
from .models import CustomUser
from django.contrib.auth.forms import UserCreationForm
from django.forms import EmailInput, PasswordInput,TextInput
from allauth.socialaccount.forms import SignupForm
from django.forms import ValidationError

class CreateUserForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = ['email', 'password1', 'password2']
        widgets = {
            'email': EmailInput(attrs={
                'class': "email",
                'id': "email",
                # 'style': 'max-width: 300px;'
                'placeholder': 'Name'
                }),
            'password1': PasswordInput(attrs={
                'class': "password", 
                'id': "password1",
                'style': 'background-color: white;',
                'placeholder': "Enter password"
                }),
            'password2': PasswordInput(attrs={
                'class': "password", 
                'id': "password",
                # 'style': 'max-width: 300px;',
                'placeholder': "Confirm password"
                })
        }
        


class CustomSignupForm(SignupForm):
     def raise_duplicate_email_error(self):
         raise ValidationError("שם משתמש כבר קיים עם כתובת אימייל")

animate99/apps/accounts/views.py
from django.http import HttpResponse
from django.shortcuts import render, redirect
from .forms import CreateUserForm
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
# Create your views here.

def register_view(request):
    if request.user.is_authenticated:
        return redirect("home")
    else:
        form = CreateUserForm()
        
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            if form.is_valid():
                form.save()
                user = form.cleaned_data.get('email')
                messages.success(request, user + ' ' +  'account created, kindly login .'  )

               
                
                
                       
                
                return redirect('accounts:login')

            
        context= {
            'form':form,
        }
        return render(request, "accounts/register.html", context)


def login_view(request):
    if request.user.is_authenticated:
        return redirect("home")
    else:
        if request.method == 'POST':
            email = request.POST.get('email')
            password = request.POST.get('password')
            
            user = authenticate(request, email=email, password=password)
            
            if user is not None:
                login(request, user)
                return redirect('library')
            else:
                messages.info(request, 'Email OR password is incorrect')           
        context= {}
        return render(request, "accounts/login.html", context )
    


# @login_required(login_url='login')
def logout_user(request):
    logout(request)
    return redirect('accounts:login')


def forgot_view(request):
    return render (request,'accounts/reset_page1.html')

def reset_view(request):
    return render (request,'accounts/reset_page2.html')

animate99/templates/accounts/login.html
{% load static %}
{% load socialaccount %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sign In</title>
    <link rel="stylesheet" href="{% static 'accounts/style.css'  %}">
    <link rel="shortcut icon" href="{% static 'main/favicon.svg' %}" type="image/x-icon">
</head>

<body>
    <header>
        <nav>
            <a href="{% url 'home' %}"><div class="anim">
                <div class="logo-head">
                    <h1>Animate</h1>
                </div>
                <div class="logo-num"><span>99</span></div>
            </div></a>
            
           
        </nav>
    </header>
    <main class="container">
        <div class="left">
            <h2>Welcome Back!</h2>
            <p>Continue to your Animate99 account to access our full library!</p>
        </div>
        <div class="right">
            <div class="right__top">
                <h2> Log In</h2>
                <a href="{% provider_login_url 'google' method='oauth2'%}" class="btn btn-google">
                    <img src="{% static 'accounts/Google - png 0.png'  %}" alt="google icon">Login with Google</a>
                <p class="login_p">Or</p>
            </div>
            <form action="./" method="POST">
                {% csrf_token %}
                <div class="email">
                    <label for="email">Email Address</label>
                    <input type="email" name="email" id="email" placeholder="Enter email address" />
                </div>
                <div class="password">
                    <label for="password">Password</label>
                    <input type="password" name="password" id="password" placeholder="Enter password"  class="pword"/>                 
                </div>
                <div class="error-message">
                {% for message in messages %}
                    <p>{{message}}</p>
                {% endfor %}
                </div>
                
                <div class="button">
                    <button class="btn btn__login">Log In</button>
                    <small>Don't have an account?
                        <span><a href= "{% url 'accounts:register' %}">Register</a></small></span>
                        
                </div>
            </form>
        </div>
    </main>
</body>

</html>




<!-- <h1>login</h1>
<form action="" method="POST">
    {% csrf_token %}
    <label for="email">email</label>
    <input type="email" name="email">
    <input type="password" name="password">
    <input type="submit">
</form>

<a href="{% provider_login_url 'google' method='oauth2'%}">google auth</a>

<a href="{% url 'account_login' %}">login 2</a>


{% for message in messages %}
<p>{{message}}</p>

{% endfor %}

animate99/templates/accounts/register.html
{% load static %}
{% load socialaccount %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Sign Up</title>
    <link rel="stylesheet" href="{% static 'accounts/style.css'  %}">
    <link rel="shortcut icon" href="{% static 'main/favicon.svg' %}" type="image/x-icon">
</head>

<body>
    <header>
        <nav>
            <a href="{% url 'home' %}"><div class="anim">
                <div class="logo-head">
                    <h1>Animate</h1>
                </div>
                <div class="logo-num"><span>99</span></div>
            </div></a>
        
        
        </nav>
    </header>
    <main class="container">
        <div class="left">
            <h2>Gain Full Access!
            </h2>
            <p>Register your account in just a few minutes to gain access to our whole library!</p>
        </div>
        <div class="right">
            <div class="right__top">
                <h2>Sign Up</h2>
                <a href="{% provider_login_url 'google' method='oauth2'%}" class="btn btn-google">
                    <img src="{% static 'accounts/Google - png 0.png'  %}" alt="google icon">Sign Up with Google</a>
                <p>Or</p>
            </div>
            <form action="./" method="POST">
                {% csrf_token %}
                <div class="email">
                    <label for="email">Email Address</label>
                    <input type="email" name="email" id="email" placeholder="Enter email address" />
                </div>
                <div class="password">
                    <label for="password">Password</label>
                    <input type="password" name="password1" id="password1" placeholder="Enter your password" />
                    {% comment %} {{form.password1}} {% endcomment %}
                    {% comment %} <input type="password" name="password" id="password" placeholder="Enter password" /> {% endcomment %}
                </div>
                <div class="password">
                    <label for="password">Confirm Password</label>
                    <input type="password" name="password2" id="password2" placeholder="Confirm Password" />
                    {% comment %} {{form.password2}} {% endcomment %}
                    {% comment %} <input type="password" name="password" id="password" placeholder="Enter password" /> {% endcomment %}
                </div>
                <div class="button">
                    <input style="background-color:#D0D6F2; border:none; color: #232946; font-family: 'Open Sans'; font-weight: bold; font-size: 1em; border-radius:0;" type="submit" name="register_user" class="my_btn__login">
                    {% comment %} <button class="btn btn__login">Register</button> {% endcomment %}
                    <small>Already have an account?
                        <span>

                            <a href="{% url 'accounts:login' %}">Sign in</a></small></span>
                </div>
            </form>

        </div>
</body>

</html>

<!-- 
{% load crispy_forms_tags %}
    <h1>Registration</h1>
<div>
    
   
    <form action="" method="POST">
        {% csrf_token %}
        <div>{{form.email.label}}{{form.email}}</div>
        <div>{{form.first_name.label}}{{form.first_name}}</div>
        <div>{{form.last_name.label}}{{form.last_name}}</div>
        <div>{{form.github_url.label}}{{form.github_url}}</div>
        <div>{{form.password1.label}}{{form.password1}}</div>
        <div>{{form.password2.label}}{{form.password2}}</div>
        
        
        <input type="submit" name="register_user">
    </form>
    <div>{{form.errors}}</div>    
</div>

<script>
		/* Because i didnt set placeholder values in forms.py they will be set here using vanilla Javascript
		//We start indexing at one because CSRF_token is considered and input field*/

		//Query All input fields
		let form_fields = document.getElementsByTagName('input')
		form_fields[1].placeholder='Email address';
		form_fields[2].placeholder='First name';
		form_fields[3].placeholder='Last name';
		form_fields[4].placeholder='github url';
        form_fields[5].placeholder='Enter password...';
        form_fields[6].placeholder='Re-enter Password...';

		for (let field in form_fields){	
			form_fields[field].className += ' form-control'
		}
</script> -->

animate99/templates/accounts/reset_page1.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Forgot Password</title>
    <link rel="stylesheet" href="{% static 'accounts/style.css'  %}">
    <link rel="shortcut icon" href="{% static 'main/favicon.svg' %}" type="image/x-icon">
</head>

<body>
    <header>
        <h1>Animate <span>99</span></h1>
    </header>
    <main class="container">
        <div class="left">
            <h2>Forgot Password?</h2>
            <p>A link would be sent to your registered email address</p>
        </div>
        <div class="right">
            <form action="./" method="post">
                <div class="password">
                    <label for="email">Email Address</label>
                    <input type="email" name="email" id="email" placeholder="Enter email address" />
                </div>
                <div class="button">
                    <button class="btn btn__login">Reset</button>
          </div>
        </form>
      </div>
    </main>
  </body>
</html>

animate99/templates/accounts/reset_page2.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Reset Password</title>
    <link rel="stylesheet" href="{% static 'accounts/style.css'  %}">
    <link rel="shortcut icon" href="{% static 'main/favicon.svg' %}" type="image/x-icon">
</head>

<body>
    <header>
        <h1>Animate <span>99</span></h1>
    </header>
    <main class="container">
        <div class="left">
            <h2>Create New Password</h2>
            <p>Your new password must be different from your previous password</p>
        </div>
        <div class="right">
            <form action="./" method="post">
                <div class="email">
                    <label for="email">New Password</label>
                    <input type="password" name="email" id="email" placeholder="Password" />
                </div>
                <div class="password">
                    <label for="email">Confirm Password</label>
                    <input type="password" name="email" id="email" placeholder="Password" />
                </div>
                <div class="button">
                    <button class="btn btn__login">Confirm</button>
                </div>
        </form>
      </div>
    </main>
  </body>
</html>